# 获取用户信息
[get_user_info]
enable = false # 开关

# 关注（直播站接口）
[follow_]
enable = false
uid_list = [99265555]

# 取消关注（直播站接口）
[delete_follow]
enable = false
uid_list = [8429322]

# 清空账号资产/信息
[destory_account]
enable = false

# 制造高仿信息
[make_fake_userinfo]
enable = false

# 随机关注
[random_follow]
enable = false

# 每日任务(观看/分享/登陆)
[level_task]
enable = false

# 一键五连(点赞/投币/收藏/观看/分享)
[combo]
enable = false
av_list = [21389666,21389665]

# 清空动态
[clean_dynamic]
enable = false

# 关注
[follow]
enable = false
uid_list = [513753189]

# 取消关注
[unfollow]
enable = false
uid_list = [513753190]

# 清空没关注自己的up
[clean_not_follow_up]
enable = false

# 清空自己没回粉的粉丝
[clean_not_follow_fan]
enable = false

# 佩戴勋章
[wear_medal]
enable = false
medal_id = 10361

# 删除勋章
[delete_medal]
enable = false
medal_id = 29245

# 显示所有勋章
[get_all_medal]
enable = false

# 发送弹幕
[send_danmu]
enable = false
msg = "哈欠带带"
roomid = 983274

# 设置隐私
[set_private]
enable = false


# 硬币兑换勋章
[coin_to_medal]
enable = false
buy_uid = 1

# 银瓜子兑换硬币
[sliver_to_coin]
enable = false

# 查询直播站实物中奖记录
[query_live_reward]
enable = false

# 实物抽奖配置
[draw_lottery]
enable = false
aid = 396
number = 1

# 查询系统通知
[query_system_notice]
enable = false

# 评论点赞
[comment_like]
enable = false
type = 1 # 作品类型(视频video:1  活动activity:4 相簿gallery:11 文章article:12)
oid = 68150115 # 作品ID
rpid = 1971683604 # 评论ID

# 评论点踩
[comment_hate]
enable = false
type = 1
oid = 68150115
rpid = 1971683604

# 评论发送
[comment_send]
enable = false
type = 1
oid = 75677777

# 评论回复
[comment_reply]
enable = false
type = 1
oid = 75677777
root = 2107420777
parent = 2107420777

# actid抽奖
[act_id_lottery]
enable = false
act_id = 247
get_chance = 1
sleep = 0.1

# 视频点赞
[video_like]
enable = false
aid = 85794878

# 视频取消点赞
[video_dislike]
enable = false
aid = 87051634

# 视频播放
[watch_video]
enable = false
aid = 85794878

# 视频播放心跳
[watch_video_heartbeat]
enable = false
aid = 85794878

# 6号直播间签到分享
[Six]
enable = false

# 漫画测试
[MangaSign]
enable = false

# 删除粉丝
[delete_fans]
enable = false
fan_uid = 198833019

# 天选
[tianxuan]
enable = false

# 测试ip，无法成功，待废弃
[test_ip]
enable = false

